name: shell-binaries
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - LambdaCase
  - OverloadedStrings
  - ViewPatterns

dependencies:
  - base
  - turtle

library:
  source-dirs: src

executable:
  bk:
    source-dirs: exe
    main-is: Bk.hs

tests:
  doctest:
    main: DocTest.hs
    source-dirs: test
    dependencies:
      - shell-binaries
      - doctest

  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - shell-binaries
      - hspec
