#!/usr/bin/env bash

# Function log_all_commands
# @description log all commands to a logfile. To be used in $PROMPT_COMMAND
if [ $(id -u) -ne 0 ]; then
  echo "$(date '+%Y-%m-%d.%H:%M:%S') $(pwd) $(history 1)" >> ~/.bash/log/bash-history-$(date '+%Y-%m-%d').log
fi


