#!/usr/bin/env bash

# Function myReload
# @description source bashrc if in shell, rebuild stack if in stack project
if [ -z "`ls | grep 'stack.yaml'`" ]; then
  source ~/.bashrc
else
  stack build
fi
