#!/usr/bin/env bash

# Function safe_path_add
# @description add path to $PATH variable, if it is not already there.
PATH_FOUND=$(echo $PATH | grep -o -E "(^|:)$1" | head -1)

if [ -z $PATH_FOUND ] && [ -d $1 ]; then
  export PATH=$PATH:$1
# else
#    test -z $PATH_FOUND && echo "$1 not a directory" || echo "$1 in PATH"
fi



