name: scripts
version: 0.1.0.0
license: MIT
license-file: ../LICENSE
github: stites/scripts/hs

ghc-options: -Wall -O2 -threaded

dependencies:
  - base
  - turtle
  - exceptions
  - text
  - optional-args
  - optparse-applicative
  - safe-exceptions
  - system-filepath # this is actually deprecated

executables:
  bk:
    source-dirs: exe
    main: Bk.hs
    other-modules: []

# replicate:
#   source-dirs: exe
#   main: Replicate.hs

# retry:
#   source-dirs: exe
#   main: Retry.hs

  monitors:
    source-dirs: exe
    main: Monitors.hs
    other-modules: []

  stacknew:
    source-dirs: exe
    main: StackNew.hs
    other-modules: []

  pocket-to-todoist:
    source-dirs: exe
    main: PocketToTodoist.hs
    other-modules: []
    dependencies:
      - wreq
      - tagsoup
      - fused-effects >= 1.0.0.0
      - monadIO
      - streaming
      - lens
      - bytestring

#  est-shares:
#    source-dirs: exe
#    main: EstShares.hs

#  link_configs:
#    source-dirs: exe
#    main: LinkConfigs.hs
#
#  save_config_links:
#    source-dirs: exe
#    main: SaveConfigLinks.hs
#
#  bash_hs_reload:
#    source-dirs: exe
#    main: BashHsReload.hs
#
#  append_history:
#    source-dirs: exe
#    main: AppendHistory.hs
#
#  log_all_commands:
#    source-dirs: exe
#    main: LogAllCommands.hs
#
#  virtual_env_prompt:
#    source-dirs: exe
#    main: VirtualEnvPrompt.hs

tests:
  doctest:
    main: DocTest.hs
    source-dirs: test
    dependencies:
      - shell-binaries
      - doctest

  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - shell-binaries
      - hspec
